[package]
name = "riscv-emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
colourful = { git = "https://github.com/todaymare/colourful" }
winit = "*"
pixels = "*"
elf = "*"

[features]
test-harness = [] 

[profile.release]
debug = true
